#FONTES
from tkinter import Widget

FONTE_TITULO = ("Arial",16,"bold")
FONTE_SUBTITULO = ("Aria,",14)
FONTE_PADRAO = ("Arial",11)

#ESPAÇAMENTOS PADY
PADY_PADRAO_SUBTITULO = (2,10)
PADY_PADRAO = 7
PADY_FORM = 15
PADY_CAMPO = 8
PADY_MENSAGEM = (0, 2)

#ESPAÇAMENTOS PADX
PADX_PADRAO = 20
PADX_LABEL = 20
PADX_CAMPO = (0,10)

#BOTOES

WIDGET_PADRAO = 25
PADY_BOTAO = 6
PADY_VOLTAR = (20,10)
